"""
Build-time vendoring tool for the grader payload.

Run this in an environment that has the pinned `swebench` and `swesmith`
installed::

    python -m examples.mini_swe.grading.vendor_parsers

It does two things:

1. Copies the official swebench `log_parsers/*.py` modules into
   `_vendor/log_parsers/`, rewriting only their imports so they resolve against
   the local `_constants`/`_utils` and no longer require `swebench`.
2. Flattens every SWE-smith *Python* profile `log_parser` method into a free
   function named `swesmith_log_parser_<sha>` and writes them to
   `_vendor/swesmith_parsers.py`.

The output is committed. `PROVENANCE.md` records the upstream versions and
per-file digests. `freeze.py` uses the same `<sha>` naming scheme, so a
prepare-time assertion can guarantee every row's parser exists in the registry.
"""

from __future__ import annotations

import ast
import hashlib
import importlib.metadata as metadata
import inspect
import logging
import re
import sys
import textwrap
from pathlib import Path

from .parsers import smith_parser_name

psrl_logger = logging.getLogger(__file__)

VENDOR_DIR = Path(__file__).resolve().parent / "_vendor"
LOG_PARSER_DIR = VENDOR_DIR / "log_parsers"

_REWRITES = (
    ("from swebench.harness.constants import TestStatus", "from .._constants import TestStatus"),
    ("from swebench.harness.utils import ansi_escape", "from .._utils import ansi_escape"),
    ("from swebench.harness.test_spec.test_spec import TestSpec\n", ""),
)


def parser_hash(source: str) -> str:
    """
    Return the stable 12-char digest used to name a flattened profile parser.
    """
    return smith_parser_name(source).rsplit("_", 1)[1]


def _rewrite(text: str) -> str:
    for old, new in _REWRITES:
        text = text.replace(old, new)
    if "from __future__ import annotations" not in text:
        text = "from __future__ import annotations\n\n" + text.lstrip("\n")
    return text


def vendor_swebench_parsers() -> list[str]:
    """
    Copy and rewrite the official swebench per-language parser modules.
    """
    import swebench.harness.log_parsers as upstream

    source_dir = Path(upstream.__file__).resolve().parent
    written: list[str] = []
    for module_path in sorted(source_dir.glob("*.py")):
        if module_path.name == "__init__.py":
            continue
        target = LOG_PARSER_DIR / module_path.name
        target.write_text(_rewrite(module_path.read_text()))
        written.append(module_path.name)
    return written


def _flatten_method(func: object, source: str) -> str:
    """
    Rewrite a `def log_parser(self, ...)` method source into a free function.
    """
    name = f"swesmith_log_parser_{parser_hash(source)}"
    flat = re.sub(r"^def log_parser\(self(?:,\s*)?", f"def {name}(", textwrap.dedent(source), count=1, flags=re.M)
    if f"def {name}(" not in flat:
        raise RuntimeError(f"Could not flatten SWE-smith parser {func!r}.")
    tree = ast.parse(flat)
    if any(isinstance(node, ast.Name) and node.id in {"self", "cls", "super"} for node in ast.walk(tree)):
        raise ValueError(f"Parser {name!r} depends on profile state and cannot be bundled as a free function.")
    return flat


def generate_swesmith_parsers() -> int:
    """
    Flatten SWE-smith Python profile parsers into `swesmith_parsers.py`.
    """
    from swesmith.profiles import registry
    from swesmith.profiles.python import PythonProfile

    distinct: dict[str, str] = {}
    for profile in registry.values():
        cls = type(profile)
        if not issubclass(cls, PythonProfile):
            continue
        source = textwrap.dedent(inspect.getsource(cls.log_parser))
        distinct.setdefault(parser_hash(source), _flatten_method(cls.log_parser, source))

    lines = [
        '"""Generated by vendor_parsers.py. Do not edit by hand.',
        "",
        "Flattened SWE-smith Python-profile log parsers, keyed by source digest.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import re",
        "",
        "from ._constants import TestStatus",
        "",
    ]
    for digest in sorted(distinct):
        lines.append(distinct[digest].rstrip())
        lines.append("")
        lines.append("")
    lines.append("SWESMITH_PARSER_BY_DIGEST = {")
    for digest in sorted(distinct):
        lines.append(f'    "{digest}": swesmith_log_parser_{digest},')
    lines.append("}")
    lines.append("")
    (VENDOR_DIR / "swesmith_parsers.py").write_text("\n".join(lines))
    return len(distinct)


def write_provenance(swesmith_count: int) -> None:
    """
    Record upstream versions and per-file digests next to the vendored code.
    """
    rows = []
    for path in sorted(VENDOR_DIR.rglob("*.py")):
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        rows.append(f"| `{path.relative_to(VENDOR_DIR).as_posix()}` | `{digest}` |")
    versions = []
    for package in ("swebench", "swesmith"):
        try:
            versions.append(f"- `{package}=={metadata.version(package)}`")
        except metadata.PackageNotFoundError:
            versions.append(f"- `{package}` (not installed)")

    body = [
        "# Vendored grading payload provenance",
        "",
        "Generated by `examples/mini_swe/grading/vendor_parsers.py`.",
        "Do not edit the copied files by hand.",
        "",
        "## Upstream versions",
        "",
        *versions,
        "",
        "## Deliberate deviations from upstream",
        "",
        "- `from swebench.harness.test_spec.test_spec import TestSpec` is removed;",
        "  `from __future__ import annotations` is injected so the annotation never",
        "  needs a runtime definition. Only the JavaScript and Ruby parsers inspect",
        "  `test_spec`, and only for `instance_id`.",
        "- `swebench.harness.utils.ansi_escape` is vendored into `_utils.py`.",
        "- `log_parsers/__init__.py` is authored locally (mirrors upstream aggregation).",
        "- The dead `test_cmd` lookup on `MAP_REPO_VERSION_TO_SPECS` in upstream",
        "  `get_logs_eval` is dropped in the local `scoring.get_logs_eval`.",
        f"- {swesmith_count} distinct SWE-smith Python profile parsers are flattened",
        "  into free functions named `swesmith_log_parser_<sha256[:12]>`.",
        "",
        "## Local scoring deviations",
        "",
        "`scoring.py` rejects empty parser output, normalizes serialized evaluation modes,",
        "and counts every nonpassing expected test as failed in pass-and-fail mode,",
        "including SKIPPED. These PSRL policies are separate from copied parsers.",
        "",
        "## File digests",
        "",
        "| File | sha256 |",
        "| --- | --- |",
        *rows,
        "",
    ]
    (VENDOR_DIR / "PROVENANCE.md").write_text("\n".join(body))


def main() -> int:
    if not LOG_PARSER_DIR.exists():
        LOG_PARSER_DIR.mkdir(parents=True)
    copied = vendor_swebench_parsers()
    swesmith_count = generate_swesmith_parsers()
    write_provenance(swesmith_count)
    psrl_logger.info(f"Vendored {len(copied)} swebench parser modules and {swesmith_count} SWE-smith parsers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
